keycloak-rel/keycloak-rel

.github/workflows/nightly.yml

Requires update to admin-ui to be merged first:
https://github.com/keycloak/keycloak-admin-ui/pull/2334
Closes #1

Add new Admin Console to nightly releases

---

.github/workflows/nightly.yml

Resolves: https://github.com/keycloak/keycloak/issues/10439

Release nightly k8s resources

---

.github/workflows/nightly.yml

Add documentation to nightly release

---

.github/workflows/x-keycloak-operator.yml

Nightly test run: 
https://github.com/keycloak-rel-testing/keycloak-rel/actions/runs/2716986905

Fix Operator

---

.github/workflows/release-nightly.yml

Closes https://github.com/keycloak-rel/keycloak-rel/issues/42
Supersedes #43.
It's not a super nice solution but if we want to avoid [external dependencies](https://github.com/andymckay/cancel-action/tree/0.2), this is the most straightforward way.

Fix nightly

---

.github/workflows/release-nightly.yml
.github/workflows/release.yml

Show workflow branch

---

.github/workflows/x-create-gh-releases.yml
.github/workflows/x-keycloak-documentation.yml
.github/workflows/x-keycloak-nodejs-admin.yml
.github/workflows/x-keycloak.yml

Overwrite existing GH releases

---

.github/workflows/branch-create.yml
.github/workflows/branch-delete.yml
.github/workflows/release-nightly.yml
.github/workflows/release.yml

Create workflow branch

---

.github/workflows/announce.yml
.github/workflows/x-keycloak-web.yml

Set link to latest docs when announcing a release

---

.github/workflows/release-nightly.yml
.github/workflows/release.yml
.github/workflows/x-keycloak-admin-console.yml
.github/workflows/x-keycloak-container.yml
.github/workflows/x-keycloak-operator.yml

Needs to be merged with https://github.com/keycloak/keycloak-ui/pull/3441
To test this PR I've temporary added the above commit to keycloak-rel-testing/keycloak-ui

New way to switch between Nexus and GitHub

---

.github/env/keycloak-rel
.github/env/keycloak-rel-testing
.github/workflows/release-nightly.yml
.github/workflows/release.yml
.github/workflows/respin-containers.yml
.github/workflows/x-env.yml
.github/workflows/x-keycloak-container.yml
.github/workflows/x-keycloak-operator.yml

Resolves #41, resolves #32
Test run for Operator respin:
https://github.com/keycloak-rel-testing/keycloak-rel/actions/runs/3149406854
Test run for Container respin:
https://github.com/keycloak-rel-testing/keycloak-rel/actions/runs/3149381732
Nightly test run:
https://github.com/keycloak-rel-testing/keycloak-rel/actions/runs/3149446504
Should be merged after https://github.com/keycloak-rel/keycloak-rel/pull/61

Publish containers to Docker Hub

---

.github/workflows/respin-containers.yml
.github/workflows/x-create-gh-releases.yml
.github/workflows/x-env.yml

Closes #66 
Re-spin Containers workflow - success [1]
Release workflow - success [2]
[1] https://github.com/keycloak-rel-testing/keycloak-rel/actions/runs/3291769475
[2] https://github.com/keycloak-rel-testing/keycloak-rel/actions/runs/3291754830
@stianst Could you please check it? Thanks

Replace ::set-output with environment variables

---

.github/workflows/release.yml
.github/workflows/x-keycloak-nodejs-admin.yml
.github/workflows/x-publish-npm.yml

Add NPM publish step for Keycloak JS

---

.github/workflows/release-nightly.yml
.github/workflows/release.yml
.github/workflows/x-create-gh-releases.yml
.github/workflows/x-create-tags.yml
.github/workflows/x-keycloak-nodejs-connect.yml
.github/workflows/x-publish-gh-releases.yml
.github/workflows/x-publish-npm.yml

Release: https://github.com/keycloak-rel-testing/keycloak-rel/actions/runs/3344071512
Nightly: https://github.com/keycloak-rel-testing/keycloak-rel/actions/runs/3344072487
Closes #29

Add Node.js Connect to the release

---

.github/workflows/x-publish-npm.yml

Force deprecation of Node.js Connect NPM package

---

.github/workflows/x-keycloak.yml

Explicitly build the documentation before deploying

---

.github/workflows/x-publish-npm.yml

Download Node.js Connect from correct repo

---

.github/workflows/x-keycloak-operator.yml

Passed `Release` flow: https://github.com/keycloak-rel-testing/keycloak-rel/actions/runs/4745879861/jobs/8429965548
**Needs to be merged with: https://github.com/keycloak/keycloak/pull/19642**

Update operator workflow for non-Jib build

---

.github/workflows/x-keycloak.yml

Test run here (only doing a nightly as there's no difference for this PR):
https://github.com/keycloak-rel-testing/keycloak-rel/actions/runs/4784380576

Update http config for Maven

---

.github/workflows/x-keycloak-operator.yml

The Maven command was missing a `-B`

Less verbose build output for the Operator

---

.github/workflows/x-keycloak-operator.yml
.github/workflows/x-keycloak-web.yml
.github/workflows/x-keycloak.yml

Upgrades all workflows to Java 17, this PR also aligns all versions of `actions/setup-java` to v3.
**Nightly run**: https://github.com/keycloak-rel-testing/keycloak-rel/actions/runs/5453516245
**Release run**: https://github.com/keycloak-rel-testing/keycloak-rel/actions/runs/5453524431
Closes #102

Upgrade workflows to Java 17

---

.github/workflows/branch-create.yml
.github/workflows/x-create-tags.yml
.github/workflows/x-keycloak-operator.yml
.github/workflows/x-keycloak-web.yml

Add release version commit to new release branches

---

.github/workflows/x-keycloak-web.yml

Fix all issues missing in GH release notes

Fix all issues missing in GH release notes

---

.github/workflows/x-keycloak-operator.yml

This is to reflect https://github.com/keycloak/keycloak/pull/26414

Fix Keycloak image tag in Operator release flow

---

.github/workflows/x-keycloak-web.yml

Use a path were always the latest API docs are stored

---

.github/workflows/x-keycloak-web.yml

Use a path were always the latest API docs are stored (#116)

---

.github/workflows/x-keycloak-container.yml

fix: add / clean labels on community images

---

.github/workflows/x-keycloak-operator.yml

Closes https://github.com/keycloak/keycloak/issues/29869
Reverts some of the changes introduced in #119.
* Normal release
* [Action](https://github.com/keycloak-rel-testing/keycloak-rel/actions/runs/9252250775)
* [K8s repo](https://github.com/keycloak-rel-testing/keycloak-k8s-resources/blob/999.0.0-20240527-1/kubernetes/kubernetes.yml#L333)
* Nightly release
* [Action](https://github.com/keycloak-rel-testing/keycloak-rel/actions/runs/9252997714)
* [K8s repo](https://github.com/keycloak-rel-testing/keycloak-k8s-resources/blob/1da427d508909248f47b0b53de187d3a3ed7a1a9/kubernetes/kubernetes.yml#L333)

Fix Operator image coordinates

---

.github/workflows/x-publish-npm.yml

Signed-off-by: Erik Jan de Wit <erikjan.dewit@gmail.com>

added admin ui to npm

---

.github/workflows/x-keycloak-web.yml

Fixes https://github.com/keycloak/keycloak/issues/31901

Fix docs-api/latest not updated with new releases

---

.github/workflows/branch-create.yml

Closes keycloak/keycloak#34147
https://github.com/keycloak-rel-testing/keycloak-rel/actions/runs/11610847715
Resulted in https://github.com/keycloak-rel-testing/keycloak/tree/release/26.1 being created with an additional commit containing the proto.lock changes.

Commit proto.lock files when creating release branch

---

.github/env/keycloak-rel
.github/env/keycloak-rel-testing
.github/workflows/release-nightly.yml
.github/workflows/release.yml
.github/workflows/x-env.yml
.github/workflows/x-keycloak-operator-hub-publish.yml
.github/workflows/x-keycloak-operator.yml

Closes keycloak/keycloak#10438

Release process for OperatorHub

---

.github/workflows/x-keycloak-operator-hub-publish.yml

[26.2] Failed release process for OperatorHub - community

---

.github/workflows/x-keycloak.yml

Signed-off-by: stianst <stianst@gmail.com>

Remove temporary printout of env

---

README.md

Signed-off-by: Bruno Oliveira da Silva <bruno@abstractj.com>
Closes #143

Update the README with clear steps to respin container images

---

.github/workflows/tag.yml
README.md

Create general release tag

---

.github/workflows/x-keycloak.yml

Remove show maven artifacts step

---

.github/workflows/x-keycloak.yml

Remove show maven artifacts step (#166)
